### ISSUE TITLE
RequestURI path is modified when path has multiple `/` characters

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#60]
We are running cf-release 183.

It appears that the gorouter is modifying the Request Path of a request if prefixed with multiple '/' characters.

Example Request: http://test.app.com/bob
Router Log in Loggregator: `GET /bob HTTP/1.1" 404 15 `

Example Request: http://test.app.com//bob     (node the `//`)
Router Log in Loggregator: `GET http://bob HTTP/1.1`

Note the addition of "http:" to the request path.  This is what I'd expect to see:
Router Log in Loggregator: `GET //bob HTTP/1.1`

I would expect the go router to pass this path to the server unchanged.

You can see similar behaviour on pws.   Though something appears to be stripping one of the slashes as you only get an error with 3 `///`.

Example pws Request: `http://boshartifacts.cloudfoundry.org///joe`
WEBrick response: `Bad Request bad URI `http://joe'.`

**Comment by narma** [comment]
Golang issue https://github.com/golang/go/issues/10433

**Comment by shalako** [comment]
golang/go#10433 says this was fixed in golang 1.5. gorouter has been updated to golang 1.5.3 in cf-release v230.

@youngm could you try v230 and see if the upgrade addresses this issue?

**Comment by youngm** [comment]
@shalako Yes we'll probably be upgrading to v230+ in 3 weeks or so.  I'll test it then.  If you want to close this now I can reopen if it is still not fixed.

**Comment by shalako** [comment]
I bypassed the ELB and opened a telnet session directly with gorouter. According to a comment in https://github.com/golang/go/issues/10433:

> there is now a way to construct this request URI. Don't use Opaque, use RawPath (or just ParseRequestURI).

```
# telnet 10.0.32.15 80
Trying 10.0.32.15...
Connected to 10.0.32.15.
Escape character is '^]'.
GET http://lattice-scoen.superman.cf-app.com/foo HTTP/1.1
Host: lattice-scoen.superman.cf-app.com

HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Wed, 03 Feb 2016 00:48:02 GMT
X-Cf-Requestid: 2a5b82a1-5e33-4092-6923-97f4e5a5f334

404 page not found
GET http://lattice-scoen.superman.cf-app.com//foo HTTP/1.1
Host: lattice-scoen.superman.cf-app.com

HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Wed, 03 Feb 2016 00:48:13 GMT
X-Cf-Requestid: 5a2ee300-4c33-4597-7e0a-d9eadbac5a43

404 page not found
GET http://lattice-scoen.superman.cf-app.com///foo HTTP/1.1
Host: lattice-scoen.superman.cf-app.com

HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Wed, 03 Feb 2016 00:48:23 GMT
X-Cf-Requestid: 72ba5e74-cf5d-4444-4240-3b7ea3f8bc89

404 page not found
```

Corresponding logs for these were:
```
2016-02-02T16:49:49.70-0800 [RTR/0]      OUT lattice-scoen.superman.cf-app.com - [03/02/2016:00:49:49 +0000] "GET http://lattice-scoen.superman.cf-app.com/foo HTTP/1.1" 404 0 19 "-" "-" 10.0.32.15:2794 x_forwarded_for:"10.0.32.15" x_forwarded_proto:"http" vcap_request_id:e19d0e6b-2808-46f4-7d0b-04e5e237ce87 response_time:0.002659661 app_id:e7b285c1-6c6d-4272-bc2d-054b826bce79

2016-02-02T16:49:59.91-0800 [RTR/0]      OUT lattice-scoen.superman.cf-app.com - [03/02/2016:00:49:59 +0000] "GET http://lattice-scoen.superman.cf-app.com//foo HTTP/1.1" 404 0 19 "-" "-" 10.0.32.15:2794 x_forwarded_for:"10.0.32.15" x_forwarded_proto:"http" vcap_request_id:13b527df-a598-4ba3-78a9-29f92ce8d06c response_time:0.002781978 app_id:e7b285c1-6c6d-4272-bc2d-054b826bce79

2016-02-02T16:50:09.12-0800 [RTR/0]      OUT lattice-scoen.superman.cf-app.com - [03/02/2016:00:50:09 +0000] "GET http://lattice-scoen.superman.cf-app.com///foo HTTP/1.1" 404 0 19 "-" "-" 10.0.32.15:2794 x_forwarded_for:"10.0.32.15" x_forwarded_proto:"http" vcap_request_id:0db0fca0-aeb5-4f2e-47c0-679430707729 response_time:0.00276622 app_id:e7b285c1-6c6d-4272-bc2d-054b826bce79
```

**Comment by youngm** [comment]
@shalako I finally got around to validating this and it is not fixed.  It appears you had a small error in your test case.  Instead of putting the entire url in the first line of the request you should have only put the path and then added a host header for the host.

The good news is the problem can be duplicated with curl. With the exception of bypassing the ELB I guess you can update your hosts file for the test if you'd prefer to use curl and by pass the ELB.  

Regardless I've updated your test cases below with the results I see with 231:

```
curl http://lattice-scoen.superman.cf-app.com//foo

curl http://lattice-scoen.superman.cf-app.com///foo
```

Outputs in loggregator:

```
2016-02-02T16:49:49.70-0800 [RTR/0]      OUT lattice-scoen.superman.cf-app.com - [03/02/2016:00:49:49 +0000] "GET http://foo HTTP/1.1" 404 0 19 "-" "-" 10.0.32.15:2794 x_forwarded_for:"10.0.32.15" x_forwarded_proto:"http" vcap_request_id:e19d0e6b-2808-46f4-7d0b-04e5e237ce87 response_time:0.002659661 app_id:e7b285c1-6c6d-4272-bc2d-054b826bce79

2016-02-02T16:49:59.91-0800 [RTR/0]      OUT lattice-scoen.superman.cf-app.com - [03/02/2016:00:49:59 +0000] "GET http:///foo HTTP/1.1" 404 0 19 "-" "-" 10.0.32.15:2794 x_forwarded_for:"10.0.32.15" x_forwarded_proto:"http" vcap_request_id:13b527df-a598-4ba3-78a9-29f92ce8d06c response_time:0.002781978 app_id:e7b285c1-6c6d-4272-bc2d-054b826bce79
```

**Comment by shalako** [comment]
Thank you for taking a closer look. I redid my test using the relative requestURI as you suggested.

```
GET // HTTP/1.1
Host: lattice.superman.cf-app.com

HTTP/1.1 301 Moved Permanently
Content-Length: 36
Content-Type: text/html; charset=utf-8
Date: Fri, 11 Mar 2016 22:26:59 GMT
Location: /
X-Vcap-Request-Id: 65118383-db82-4f5f-631c-91abccf52774

<a href="/">Moved Permanently</a>.
```

log
```
2016-03-11T14:27:44.23-0800 [RTR/0]      OUT lattice.superman.cf-app.com - [11/03/2016:22:27:44 +0000] "GET http:// HTTP/1.1" 301 0 36 "-" "-" 10.0.48.66:39758 x_forwarded_for:"10.0.48.66" x_forwarded_proto:"http" vcap_request_id:61e9a0c6-667a-489c-6b92-b3e2a27bcae2 response_time:0.002656648 app_id:12d5c752-5c37-46bd-9bfa-00740af27b94
```

```
GET /// HTTP/1.1
Host: lattice.superman.cf-app.com

HTTP/1.1 200 OK
Content-Length: 1677
Date: Fri, 11 Mar 2016 22:28:11 GMT
X-Vcap-Request-Id: 6aede386-9ae7-4856-5621-0667cd149837

```

log
```
2016-03-11T14:28:56.87-0800 [RTR/0]      OUT lattice.superman.cf-app.com - [11/03/2016:22:28:56 +0000] "GET http:/// HTTP/1.1" 200 0 1677 "-" "-" 10.0.48.66:39758 x_forwarded_for:"10.0.48.66" x_forwarded_proto:"http" vcap_request_id:53a6f182-4dc7-4c4b-75dd-cc239e0cab23 response_time:0.002785987 app_id:12d5c752-5c37-46bd-9bfa-00740af27b94
```

I see in the logs that `http://` is prepended to the paths in both requests. However, `//` is redirected to `/` while `///` gets passed through unchanged.

I see similar behavior when going through the ELB:

```
$ curl lattice.superman.cf-app.com// -v* Adding handle: conn: 0x7fd8bb004400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fd8bb004400) send_pipe: 1, recv_pipe: 0
* About to connect() to lattice.superman.cf-app.com port 80 (#0)
*   Trying 52.72.161.118...
* Connected to lattice.superman.cf-app.com (52.72.161.118) port 80 (#0)
> GET // HTTP/1.1
> User-Agent: curl/7.30.0
> Host: lattice.superman.cf-app.com
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 36
< Content-Type: text/html; charset=utf-8
< Date: Fri, 11 Mar 2016 22:31:15 GMT
< Location: /
< X-Vcap-Request-Id: c15487ba-e791-494e-7665-8f9043495322
<
<a href="/">Moved Permanently</a>.

* Connection #0 to host lattice.superman.cf-app.com left intact
```

log
```
2016-03-11T14:32:00.14-0800 [RTR/0]      OUT lattice.superman.cf-app.com - [11/03/2016:22:32:00 +0000] "GET http:// HTTP/1.1" 301 0 36 "-" "curl/7.30.0" 10.0.2.160:46403 x_forwarded_for:"10.0.2.160" x_forwarded_proto:"http" vcap_request_id:3a90efee-0e0b-438b-4dbd-d875e4a36aba response_time:0.002452937 app_id:12d5c752-5c37-46bd-9bfa-00740af27b94
```

```
$ curl lattice.superman.cf-app.com/// -v
* Adding handle: conn: 0x7fc200804400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc200804400) send_pipe: 1, recv_pipe: 0
* About to connect() to lattice.superman.cf-app.com port 80 (#0)
*   Trying 52.72.161.118...
* Connected to lattice.superman.cf-app.com (52.72.161.118) port 80 (#0)
> GET /// HTTP/1.1
> User-Agent: curl/7.30.0
> Host: lattice.superman.cf-app.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 1677
< Date: Fri, 11 Mar 2016 22:32:19 GMT
< X-Vcap-Request-Id: 69b3117a-ed15-4503-64b9-83d5c679774f
<
...
* Connection #0 to host lattice.superman.cf-app.com left intact
```

log
```
2016-03-11T14:33:04.08-0800 [RTR/0]      OUT lattice.superman.cf-app.com - [11/03/2016:22:33:04 +0000] "GET http:/// HTTP/1.1" 200 0 1677 "-" "curl/7.30.0" 10.0.2.160:46458 x_forwarded_for:"10.0.2.160" x_forwarded_proto:"http" vcap_request_id:6a9e9bdc-6cd9-4ad8-5f2c-bfb6bc3c0ead response_time:0.002803724 app_id:12d5c752-5c37-46bd-9bfa-00740af27b94
```

Rather than preventing `http://` from being prepended, it appears it is now prepended all the time? I'd have to compare against an older version. I'm also curious about the redirect. We'll look into it.

**Comment by shashwathi** [comment]
Using RawPath in URL in place of Opaque solves the issues with double (multiple) slashes but fails for absolute URI (https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy_test.go#L233) and reserved characters (https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy_test.go#L890). We are not sure we want to break other usecases to support this case.

Regards,
@atulkc and @shashwathi

**Comment by youngm** [comment]
@shashwathi @atulkc Understandable and I agree.  So, do we put this back into the golang bug tracker and continue waiting?

**Comment by atulkc** [comment]
@youngm Yes, I think we should wait on golang fix for this one. 

Do you want to close this issue or keep it open for tracking?

**Comment by youngm** [comment]
@atulkc I'd like to keep it open.  Have you submitted a golang bug for this?

**Comment by crhino** [comment]
This is the issue on Golang that specified this behavior in 2013: https://github.com/golang/go/issues/4860
This is the code that is implementing this behavior: https://github.com/golang/go/blob/release-branch.go1.5/src/net/url/url.go#L861-L863

We submitted issue https://github.com/golang/go/issues/14952 to the golang repo.

**Comment by youngm** [comment]
Looks great.  Thanks @crhino

**Comment by shalako** [comment]
@youngm Looking at latest comments in golang/go#14952, I would opt for the switch strategy, rather than writing an alternate version of gorouter. Consider that even if @bradfitz takes this feature on, I expect it wouldn't be available until golang 1.7, so this doesn't appear to be a near-term solution.

**Comment by youngm** [comment]
@shalako I agree.  My hunch is that a switch strategy is extremely unlikely for golang anytime in the future let alone the next couple of versions unless your team can make a really good case for one. :)

That said, I hope that this limitation and perhaps other missing features like HTTP/2, persistent connections, higher layer support for more protocols than http, more commonality with tcp routing, etc. might eventually make for enough reasons rewrite all of gorouter's as a `net` product.

Do you see any possibility of something like that happening in the nearish to mid term future?

**Comment by shalako** [comment]
I don't believe we have any plans to rewrite gorouter anytime soon. Using the `net` library instead of `net/http` is an implementation detail. Though this may be driven by use cases; it's very hard to say at this point.

I have received requests for HTTP/2 support, and will be taking a closer look when we get closer to upgrading to golang 1.6. However, there are some issues with golang's implementation as I recall.

For protocols other than http, we'll be offering TCP routing. This is lower-level support, however. There has been a lot of interest in support for specific UDP protocols, and rather than stuff this all into one component, our current strategy will be to enable a "bring your own router" workflow (exposing Routing API and a multi-tenant service). This could also support routers supporting higher-layer TCP protocols.

Except for this one, I don't currently have use cases for turning gorouter into a something which is not http-specific. I would love to hear what you're imagining. 

Thank you!

**Comment by youngm** [comment]
@shalako I was under the impression from conversations with others in the past that making the gorouter a replaceable component wasn't something CF was interested in considering.

If the thought is that you want to keep gorouter relatively light and press more specialized load balancing features towards thirdparty ELBs then I agree that building a `net` based load balancer is not the direction you want to go in.

I whole heatedly agree that a "bring your own router" approach is an excellent long term strategic approach to take for this issue and ones that may popup like it.

I'd be fine if you want to close this issue for now.  If the situation changes we can reopen.
